<?php

declare(strict_types=1);

/**
 * Regenerate Tailwind scan partials from PHP class maps.
 *
 * Usage: php scripts/build-tailwind-scan.php
 */

use Ivanfuhr\BladexComponents\BladexComponentsServiceProvider;
use Ivanfuhr\BladexComponents\Support\Button\ButtonClassMap;

$root = dirname(__DIR__);

require $root.'/vendor/autoload.php';

$app = require $root.'/vendor/orchestra/testbench-core/laravel/bootstrap/app.php';

$provider = new BladexComponentsServiceProvider($app);
$provider->register();
$provider->boot();

$probe = app(ButtonClassMap::class)->tailwindContentProbe();

$targetDir = $root.'/resources/views/components/_tailwind';
$targetPath = $targetDir.'/button.blade.php';

if (! is_dir($targetDir) && ! mkdir($targetDir, 0755, true) && ! is_dir($targetDir)) {
    fwrite(STDERR, "Could not create directory: {$targetDir}\n");
    exit(1);
}

$contents = <<<BLADE
{{-- Generated by scripts/build-tailwind-scan.php — do not edit by hand. --}}
<div
    class="{$probe}"
    hidden
    aria-hidden="true"
    data-bladex-tailwind-scan="button"
></div>

BLADE;

file_put_contents($targetPath, $contents);

fwrite(STDOUT, "Wrote {$targetPath}\n");
